In [1]:
from IPython.display import display
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [2]:
INPUT_FILE = Path(
    r"C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\optimized\ED_Visits.csv"
)

OUTPUT_FOLDER = Path(
    r"C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\Explorer Dataset"
)

OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = OUTPUT_FOLDER / "ED_Visits.csv"

In [3]:
df = pd.read_csv(INPUT_FILE)

print("=" * 90)
print("ED VISITS DATASET LOADED")
print("=" * 90)

display(df.head())

==========================================================================================
ED VISITS DATASET LOADED
==========================================================================================

,fiscal_year,triage_level,visit_disposition,main_problem,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,ctas_urgency_score,is_admitted
0,2021-2022,Resuscitation,Discharged home,Acute myocardial infarction,7,36.0,2021,0.6,1,0
1,2021-2022,Resuscitation,Discharged home,Asthma,813,252.0,2021,4.2,1,0
2,2021-2022,Resuscitation,Discharged home,Pneumonia,353,198.0,2021,3.3,1,0
3,2021-2022,Resuscitation,Discharged home,Influenzal pneumonia,0,0.0,2021,0.0,1,0
4,2021-2022,Resuscitation,Discharged home,Trauma,4095,258.0,2021,4.3,1,0

In [4]:
print("\nDataset Shape")
print(df.shape)

print("\nColumn Names")
print(df.columns.tolist())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

Dataset Shape
(8512, 10)

Column Names
['fiscal_year', 'triage_level', 'visit_disposition', 'main_problem', 'ed_visits', 'median_length_of_stay_min', 'fiscal_year_start', 'length_of_stay_hours', 'ctas_urgency_score', 'is_admitted']

Missing Values
fiscal_year                  0
triage_level                 0
visit_disposition            0
main_problem                 0
ed_visits                    0
median_length_of_stay_min    0
fiscal_year_start            0
length_of_stay_hours         0
ctas_urgency_score           0
is_admitted                  0
dtype: int64

Duplicate Rows
0

In [5]:
df.rename(
    columns={
        "median_length_of_stay_min": "median_los_minutes",
        "length_of_stay_hours": "median_los_hours",
        "is_admitted": "admission_status"
    },
    inplace=True
)

In [6]:
ctas_mapping = {

    "Resuscitation": "CTAS I - Resuscitation",

    "Emergent": "CTAS II - Emergent",

    "Urgent": "CTAS III - Urgent",

    "Less Urgent": "CTAS IV - Less Urgent",

    "Non Urgent": "CTAS V - Non-Urgent",

    "Non-Urgent": "CTAS V - Non-Urgent"

}

df["triage_level"] = (
    df["triage_level"]
      .astype(str)
      .str.strip()
      .replace(ctas_mapping)
)

In [7]:
df["admission_status"] = (
    df["admission_status"]
      .replace({
          0: "Not Admitted",
          1: "Admitted"
      })
)

In [8]:
df["median_los_minutes"] = (
    pd.to_numeric(
        df["median_los_minutes"],
        errors="coerce"
    )
    .round()
    .astype(int)
)

df["median_los_hours"] = (
    df["median_los_minutes"] / 60
).round(2)

In [9]:
df = (
    df.sort_values(
        by=[
            "fiscal_year_start",
            "ctas_urgency_score",
            "admission_status",
            "visit_disposition",
            "main_problem"
        ],
        ascending=[
            False,
            True,
            True,
            True,
            True
        ]
    )
    .reset_index(drop=True)
)

In [10]:
df = df[
    [
        "fiscal_year",
        "fiscal_year_start",
        "triage_level",
        "ctas_urgency_score",
        "visit_disposition",
        "main_problem",
        "admission_status",
        "ed_visits",
        "median_los_minutes",
        "median_los_hours"
    ]
]

In [11]:
print("\nRows")
print(len(df))

print("\nColumns")
print(len(df.columns))

print("\nColumn Names")
print(df.columns.tolist())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

print("\nCTAS Levels")
print(df["triage_level"].unique())

print("\nAdmission Status")
print(df["admission_status"].value_counts())

print("\nFiscal Years")
print(df["fiscal_year"].unique())

print("\nVisit Disposition")
print(df["visit_disposition"].unique())

print("\nMain Problems")
print(df["main_problem"].nunique())

Rows
8512

Columns
10

Column Names
['fiscal_year', 'fiscal_year_start', 'triage_level', 'ctas_urgency_score', 'visit_disposition', 'main_problem', 'admission_status', 'ed_visits', 'median_los_minutes', 'median_los_hours']

Missing Values
fiscal_year           0
fiscal_year_start     0
triage_level          0
ctas_urgency_score    0
visit_disposition     0
main_problem          0
admission_status      0
ed_visits             0
median_los_minutes    0
median_los_hours      0
dtype: int64

Duplicate Rows
0

CTAS Levels
<StringArray>
['CTAS I - Resuscitation',     'CTAS II - Emergent',      'CTAS III - Urgent',
            'Less urgent',             'Non-urgent',                'Unknown',
                  'Total']
Length: 7, dtype: str

Admission Status
admission_status
Not Admitted    7448
Admitted        1064
Name: count, dtype: int64

Fiscal Years
<StringArray>
['2021-2022', '2020-2021', '2019-2020', '2018-2019', '2017-2018', '2016-2017',
 '2015-2016', '2014-2015', '2013-2014', '2012-2013', '2011-2012', '2010-2011',
 '2009-2010', '2008-2009', '2007-2008', '2006-2007', '2005-2006', '2004-2005',
 '2003-2004']
Length: 19, dtype: str

Visit Disposition
<StringArray>
[               'Admitted',                   'Death',
         'Discharged home', 'Intra-facility transfer',
        'Not seen or left',                   'Total',
             'Transferred',                 'Unknown']
Length: 8, dtype: str

Main Problems
8

In [12]:
print("\nFirst 20 Rows")
display(df.head(20))

print("\nLast 20 Rows")
display(df.tail(20))

First 20 Rows

,fiscal_year,fiscal_year_start,triage_level,ctas_urgency_score,visit_disposition,main_problem,admission_status,ed_visits,median_los_minutes,median_los_hours
0,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Acute myocardial infarction,Admitted,1360,93,1.55
1,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Any,Admitted,77562,420,7.00
2,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Asthma,Admitted,822,456,7.60
3,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Influenzal pneumonia,Admitted,0,0,0.00
4,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Motor vehicle collisions,Admitted,3032,324,5.40
5,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Pneumonia,Admitted,1656,561,9.35
6,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Trauma,Admitted,8476,348,5.80
7,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Unintentional falls,Admitted,2393,456,7.60
8,2021-2022,2021,CTAS I - Resuscitation,1,Death,Acute myocardial infarction,Not Admitted,365,36,0.60
9,2021-2022,2021,CTAS I - Resuscitation,1,Death,Any,Not Admitted,11081,42,0.70
10,2021-2022,2021,CTAS I - Resuscitation,1,Death,Asthma,Not Admitted,0,18,0.30
11,2021-2022,2021,CTAS I - Resuscitation,1,Death,Influenzal pneumonia,Not Admitted,0,0,0.00
12,2021-2022,2021,CTAS I - Resuscitation,1,Death,Motor vehicle collisions,Not Admitted,195,30,0.50
13,2021-2022,2021,CTAS I - Resuscitation,1,Death,Pneumonia,Not Admitted,32,324,5.40
14,2021-2022,2021,CTAS I - Resuscitation,1,Death,Trauma,Not Admitted,683,60,1.00
15,2021-2022,2021,CTAS I - Resuscitation,1,Death,Unintentional falls,Not Admitted,120,201,3.35
16,2021-2022,2021,CTAS I - Resuscitation,1,Discharged home,Acute myocardial infarction,Not Admitted,7,36,0.60
17,2021-2022,2021,CTAS I - Resuscitation,1,Discharged home,Any,Not Admitted,37243,294,4.90
18,2021-2022,2021,CTAS I - Resuscitation,1,Discharged home,Asthma,Not Admitted,813,252,4.20
19,2021-2022,2021,CTAS I - Resuscitation,1,Discharged home,Influenzal pneumonia,Not Admitted,0,0,0.00

Last 20 Rows

,fiscal_year,fiscal_year_start,triage_level,ctas_urgency_score,visit_disposition,main_problem,admission_status,ed_visits,median_los_minutes,median_los_hours
8492,2003-2004,2003,CTAS III - Urgent,3,Unknown,Motor vehicle collisions,Not Admitted,283,82,1.37
8493,2003-2004,2003,Less urgent,3,Unknown,Motor vehicle collisions,Not Admitted,308,64,1.07
8494,2003-2004,2003,Non-urgent,3,Unknown,Motor vehicle collisions,Not Admitted,0,42,0.70
8495,2003-2004,2003,Unknown,3,Unknown,Motor vehicle collisions,Not Admitted,0,0,0.00
8496,2003-2004,2003,Total,3,Unknown,Motor vehicle collisions,Not Admitted,657,76,1.27
8497,2003-2004,2003,CTAS III - Urgent,3,Unknown,Pneumonia,Not Admitted,282,103,1.72
8498,2003-2004,2003,Less urgent,3,Unknown,Pneumonia,Not Admitted,247,78,1.30
8499,2003-2004,2003,Non-urgent,3,Unknown,Pneumonia,Not Admitted,0,79,1.32
8500,2003-2004,2003,Unknown,3,Unknown,Pneumonia,Not Admitted,0,0,0.00
8501,2003-2004,2003,Total,3,Unknown,Pneumonia,Not Admitted,590,98,1.63
8502,2003-2004,2003,CTAS III - Urgent,3,Unknown,Trauma,Not Admitted,3007,67,1.12
8503,2003-2004,2003,Less urgent,3,Unknown,Trauma,Not Admitted,6660,60,1.00
8504,2003-2004,2003,Non-urgent,3,Unknown,Trauma,Not Admitted,109,41,0.68
8505,2003-2004,2003,Unknown,3,Unknown,Trauma,Not Admitted,0,0,0.00
8506,2003-2004,2003,Total,3,Unknown,Trauma,Not Admitted,10029,62,1.03
8507,2003-2004,2003,CTAS III - Urgent,3,Unknown,Unintentional falls,Not Admitted,895,85,1.42
8508,2003-2004,2003,Less urgent,3,Unknown,Unintentional falls,Not Admitted,1557,69,1.15
8509,2003-2004,2003,Non-urgent,3,Unknown,Unintentional falls,Not Admitted,18,42,0.70
8510,2003-2004,2003,Unknown,3,Unknown,Unintentional falls,Not Admitted,0,0,0.00
8511,2003-2004,2003,Total,3,Unknown,Unintentional falls,Not Admitted,2546,76,1.27

In [13]:
df["triage_level"] = (
    df["triage_level"]
    .astype(str)
    .str.strip()
)

# Remove rows where triage_level = Total
df = df[
    df["triage_level"].str.lower() != "total"
].copy()

In [14]:
print(df["triage_level"].unique())

print("\nValue Counts")
print(df["triage_level"].value_counts())

print(f"\nTotal Rows Remaining: {len(df):,}")

<StringArray>
['CTAS I - Resuscitation',     'CTAS II - Emergent',      'CTAS III - Urgent',
            'Less urgent',             'Non-urgent',                'Unknown']
Length: 6, dtype: str

Value Counts
triage_level
CTAS I - Resuscitation    1216
CTAS II - Emergent        1216
CTAS III - Urgent         1216
Less urgent               1216
Non-urgent                1216
Unknown                   1216
Name: count, dtype: int64

Total Rows Remaining: 7,296

In [15]:
# ============================================================
# STANDARDIZE VISIT DISPOSITION
# ============================================================

df["visit_disposition"] = (
    df["visit_disposition"]
    .astype(str)
    .str.strip()
    .str.title()
)

visit_disposition_mapping = {

    "Discharged":"Discharged",

    "Admitted":"Admitted",

    "Transferred":"Transferred",

    "Left Without Being Seen":"Left Without Being Seen",

    "Left Against Medical Advice":"Left Against Medical Advice",

    "Died":"Died"

}

df["visit_disposition"] = (
    df["visit_disposition"]
    .replace(visit_disposition_mapping)
)

print(df["visit_disposition"].value_counts())

visit_disposition
Admitted                   912
Death                      912
Discharged Home            912
Intra-Facility Transfer    912
Not Seen Or Left           912
Total                      912
Transferred                912
Unknown                    912
Name: count, dtype: int64

In [16]:
df["main_problem"] = (
    df["main_problem"]
    .astype(str)
    .str.strip()
    .str.title()
    .str.replace(r"\s+", " ", regex=True)
)

print(df["main_problem"].nunique())

8

In [17]:
df["ed_visits"] = (
    pd.to_numeric(
        df["ed_visits"],
        errors="coerce"
    )
    .fillna(0)
    .astype("int64")
)

print(df["ed_visits"].dtype)

int64

In [18]:
df["admission_flag"] = (
    df["admission_status"]
    .map({
        "Not Admitted":0,
        "Admitted":1
    })
    .astype(int)
)

display(
    df[
        [
            "admission_status",
            "admission_flag"
        ]
    ].head()
)

  admission_status  admission_flag
0         Admitted               1
1         Admitted               1
2         Admitted               1
3         Admitted               1
4         Admitted               1

In [19]:
duplicate_keys = [

    "fiscal_year",

    "triage_level",

    "visit_disposition",

    "main_problem",

    "admission_status"

]

duplicates = df[
    df.duplicated(
        subset=duplicate_keys,
        keep=False
    )
]

print("Duplicate Analytical Records")

print(len(duplicates))

display(
    duplicates.sort_values(
        duplicate_keys
    ).head(50)
)

Duplicate Analytical Records
0

Empty DataFrame
Columns: [fiscal_year, fiscal_year_start, triage_level, ctas_urgency_score, visit_disposition, main_problem, admission_status, ed_visits, median_los_minutes, median_los_hours, admission_flag]
Index: []

In [20]:
if len(duplicates) > 0:

    df = (

        df.groupby(

            duplicate_keys,

            as_index=False

        )

        .agg({

            "ed_visits":"sum",

            "median_los_minutes":"median",

            "median_los_hours":"median",

            "ctas_urgency_score":"first",

            "fiscal_year_start":"first",

            "admission_flag":"first"

        })

    )

print(df.shape)

(7296, 11)

In [21]:
df["erbi"] = df["ed_visits"] * df["median_los_minutes"]

In [23]:
# Remove rows where visit_disposition is "Total"
df = df[df["visit_disposition"].str.strip().str.lower() != "total"]

# Remove rows where main_problem is "Any"
df = df[df["main_problem"].str.strip().str.lower() != "any"]

# Reset row index
df = df.reset_index(drop=True)

In [24]:
print("Visit Disposition values:")
print(df["visit_disposition"].unique())

Visit Disposition values:
<StringArray>
[               'Admitted',                   'Death',
         'Discharged Home', 'Intra-Facility Transfer',
        'Not Seen Or Left',             'Transferred',
                 'Unknown']
Length: 7, dtype: str

In [25]:
print("\nMain Problem values:")
print(df["main_problem"].unique())

Main Problem values:
<StringArray>
['Acute Myocardial Infarction',                      'Asthma',
        'Influenzal Pneumonia',    'Motor Vehicle Collisions',
                   'Pneumonia',                      'Trauma',
         'Unintentional Falls']
Length: 7, dtype: str

In [26]:
print("\nUpdated dataset shape:", df.shape)

Updated dataset shape: (5586, 12)

In [27]:
display(df.head())

,fiscal_year,fiscal_year_start,triage_level,ctas_urgency_score,visit_disposition,main_problem,admission_status,ed_visits,median_los_minutes,median_los_hours,admission_flag,erbi
0,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Acute Myocardial Infarction,Admitted,1360,93,1.55,1,126480
1,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Asthma,Admitted,822,456,7.60,1,374832
2,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Influenzal Pneumonia,Admitted,0,0,0.00,1,0
3,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Motor Vehicle Collisions,Admitted,3032,324,5.40,1,982368
4,2021-2022,2021,CTAS I - Resuscitation,1,Admitted,Pneumonia,Admitted,1656,561,9.35,1,929016

In [29]:
df.to_csv("ED_Visits_Cleaned.csv", index=False)

print("Dataset saved successfully as ED_Visits_Cleaned.csv")

Dataset saved successfully as ED_Visits_Cleaned.csv