In [1]:
from IPython.display import display
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [2]:
INPUT_FILE = Path(
    r"C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\optimized\Main_Problems.csv"
)

OUTPUT_FOLDER = Path(
    r"C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\Explorer Dataset"
)

OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = OUTPUT_FOLDER / "Main_Problems.csv"

In [3]:
df = pd.read_csv(INPUT_FILE)

print("="*90)
print("MAIN PROBLEMS DATASET LOADED SUCCESSFULLY")
print("="*90)

==========================================================================================
MAIN PROBLEMS DATASET LOADED SUCCESSFULLY
==========================================================================================

In [4]:
print("\nFIRST 10 ROWS")
display(df.head(10))

print("\nLAST 10 ROWS")
display(df.tail(10))

FIRST 10 ROWS

,fiscal_year,sex,main_problem,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category
0,2021-2022,All,Acute myocardial infarction,00–19,12,342.0,2021,5.7,Adult
1,2021-2022,All,Acute myocardial infarction,20–44,1231,294.0,2021,4.9,Adult
2,2021-2022,All,Acute myocardial infarction,45–64,9630,324.0,2021,5.4,Adult
3,2021-2022,All,Acute myocardial infarction,65+,15620,438.0,2021,7.3,Senior
4,2021-2022,All,Acute myocardial infarction,Total,26493,390.0,2021,6.5,Adult
5,2021-2022,All,Asthma,00–19,18888,222.0,2021,3.7,Adult
6,2021-2022,All,Asthma,20–44,12479,180.0,2021,3.0,Adult
7,2021-2022,All,Asthma,45–64,5823,216.0,2021,3.6,Adult
8,2021-2022,All,Asthma,65+,2947,270.0,2021,4.5,Senior
9,2021-2022,All,Asthma,Total,40137,210.0,2021,3.5,Adult

LAST 10 ROWS

,fiscal_year,sex,main_problem,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category
1984,2003-2004,Male,Unintentional falls,00–19,72683,107.0,2003,1.78,Adult
1985,2003-2004,Male,Unintentional falls,20–44,44930,123.0,2003,2.05,Adult
1986,2003-2004,Male,Unintentional falls,45–64,28700,140.0,2003,2.33,Adult
1987,2003-2004,Male,Unintentional falls,65+,26121,184.0,2003,3.07,Senior
1988,2003-2004,Male,Unintentional falls,Total,172434,125.0,2003,2.08,Adult
1989,2003-2004,Male,Motor vehicle collisions,00–19,22377,115.0,2003,1.92,Adult
1990,2003-2004,Male,Motor vehicle collisions,20–44,28964,135.0,2003,2.25,Adult
1991,2003-2004,Male,Motor vehicle collisions,45–64,10943,145.0,2003,2.42,Adult
1992,2003-2004,Male,Motor vehicle collisions,65+,3640,160.0,2003,2.67,Senior
1993,2003-2004,Male,Motor vehicle collisions,Total,65924,130.0,2003,2.17,Adult

In [5]:
print("\nDataset Shape")
print(df.shape)

print("\nColumn Names")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

Dataset Shape
(1994, 9)

Column Names
['fiscal_year', 'sex', 'main_problem', 'age_group', 'ed_visits', 'median_length_of_stay_min', 'fiscal_year_start', 'length_of_stay_hours', 'age_broad_category']

Data Types
fiscal_year                      str
sex                              str
main_problem                     str
age_group                        str
ed_visits                      int64
median_length_of_stay_min    float64
fiscal_year_start              int64
length_of_stay_hours         float64
age_broad_category               str
dtype: object

In [6]:
print("\nMissing Values")

display(df.isnull().sum())
print("\nDuplicate Rows")

print(df.duplicated().sum())

Missing Values

fiscal_year                  0
sex                          0
main_problem                 0
age_group                    0
ed_visits                    0
median_length_of_stay_min    0
fiscal_year_start            0
length_of_stay_hours         0
age_broad_category           0
dtype: int64

Duplicate Rows
0

In [7]:
print("\nSummary Statistics")

display(df.describe(include="all"))

Summary Statistics

,fiscal_year,sex,main_problem,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category
count,1994,1994,1994,1994,1.994000e+03,1994.00000,1994.000000,1994.000000,1994
unique,19,3,7,5,NaN,NaN,NaN,NaN,2
top,2021-2022,All,Asthma,20–44,NaN,NaN,NaN,NaN,Adult
freq,105,665,285,399,NaN,NaN,NaN,NaN,1595
mean,NaN,NaN,NaN,NaN,9.573090e+04,201.22317,2012.003009,3.353781,NaN
std,NaN,NaN,NaN,NaN,2.212879e+05,98.93799,5.478324,1.648988,NaN
min,NaN,NaN,NaN,NaN,0.000000e+00,0.00000,2003.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,4.076750e+03,140.00000,2007.000000,2.330000,NaN
50%,NaN,NaN,NaN,NaN,1.831450e+04,168.00000,2012.000000,2.800000,NaN
75%,NaN,NaN,NaN,NaN,7.413275e+04,226.75000,2017.000000,3.777500,NaN
max,NaN,NaN,NaN,NaN,2.022452e+06,1264.00000,2021.000000,21.070000,NaN

In [8]:
print("\nFiscal Years")

display(df["fiscal_year"].value_counts())

print("\nSex")

display(df["sex"].value_counts())

print("\nAge Groups")

display(df["age_group"].value_counts())

print("\nMain Problems")

print(df["main_problem"].nunique())

display(df["main_problem"].value_counts().head(20))

Fiscal Years

fiscal_year
2021-2022    105
2020-2021    105
2019-2020    105
2018-2019    105
2017-2018    105
2016-2017    105
2015-2016    105
2014-2015    105
2013-2014    105
2012-2013    105
2011-2012    105
2010-2011    105
2009-2010    105
2008-2009    105
2007-2008    105
2005-2006    105
2004-2005    105
2003-2004    105
2006-2007    104
Name: count, dtype: int64

Sex

sex
All       665
Male      665
Female    664
Name: count, dtype: int64

Age Groups

age_group
20–44    399
45–64    399
65+      399
Total    399
00–19    398
Name: count, dtype: int64

Main Problems
7

main_problem
Asthma                         285
Pneumonia                      285
Influenzal pneumonia           285
Trauma                         285
Unintentional falls            285
Motor vehicle collisions       285
Acute myocardial infarction    284
Name: count, dtype: int64

In [9]:
print("\nED Visits")

display(df["ed_visits"].describe())

print("\nMedian Length of Stay")

display(df["median_length_of_stay_min"].describe())

print("\nLength of Stay (Hours)")

display(df["length_of_stay_hours"].describe())

ED Visits

count    1.994000e+03
mean     9.573090e+04
std      2.212879e+05
min      0.000000e+00
25%      4.076750e+03
50%      1.831450e+04
75%      7.413275e+04
max      2.022452e+06
Name: ed_visits, dtype: float64

Median Length of Stay

count    1994.00000
mean      201.22317
std        98.93799
min         0.00000
25%       140.00000
50%       168.00000
75%       226.75000
max      1264.00000
Name: median_length_of_stay_min, dtype: float64

Length of Stay (Hours)

count    1994.000000
mean        3.353781
std         1.648988
min         0.000000
25%         2.330000
50%         2.800000
75%         3.777500
max        21.070000
Name: length_of_stay_hours, dtype: float64

In [10]:
print("DATA QUALITY REPORT")
print("-"*90)

print(f"Rows               : {df.shape[0]:,}")

print(f"Columns            : {df.shape[1]}")

print(f"Duplicate Rows     : {df.duplicated().sum()}")

print(f"Missing Cells      : {df.isnull().sum().sum()}")

print("\nMissing Values By Column")

display(df.isnull().sum())

DATA QUALITY REPORT
------------------------------------------------------------------------------------------
Rows               : 1,994
Columns            : 9
Duplicate Rows     : 0
Missing Cells      : 0

Missing Values By Column

fiscal_year                  0
sex                          0
main_problem                 0
age_group                    0
ed_visits                    0
median_length_of_stay_min    0
fiscal_year_start            0
length_of_stay_hours         0
age_broad_category           0
dtype: int64

In [11]:
print("\nTop 20 Main Problems by Frequency")

display(
    df["main_problem"]
    .value_counts()
    .head(20)
)

Top 20 Main Problems by Frequency

main_problem
Asthma                         285
Pneumonia                      285
Influenzal pneumonia           285
Trauma                         285
Unintentional falls            285
Motor vehicle collisions       285
Acute myocardial infarction    284
Name: count, dtype: int64

In [12]:
print("\nTop 20 Records by ED Visits")

display(
    df.nlargest(
        20,
        "ed_visits"
    )
)

Top 20 Records by ED Visits

,fiscal_year,sex,main_problem,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category
444,2017-2018,All,Trauma,Total,2022452,132.0,2017,2.20,Adult
339,2018-2019,All,Trauma,Total,2008556,138.0,2018,2.30,Adult
549,2016-2017,All,Trauma,Total,1990351,126.0,2016,2.10,Adult
234,2019-2020,All,Trauma,Total,1973292,138.0,2019,2.30,Adult
654,2015-2016,All,Trauma,Total,1923974,126.0,2015,2.10,Adult
864,2013-2014,All,Trauma,Total,1882654,120.0,2013,2.00,Adult
759,2014-2015,All,Trauma,Total,1881063,126.0,2014,2.10,Adult
24,2021-2022,All,Trauma,Total,1852364,150.0,2021,2.50,Adult
969,2012-2013,All,Trauma,Total,1837921,122.0,2012,2.03,Adult
1074,2011-2012,All,Trauma,Total,1814114,123.0,2011,2.05,Adult
1179,2010-2011,All,Trauma,Total,1772139,124.0,2010,2.07,Adult
129,2020-2021,All,Trauma,Total,1548416,126.0,2020,2.10,Adult
1703,2005-2006,All,Trauma,Total,1315584,120.0,2005,2.00,Adult
1494,2007-2008,All,Trauma,Total,1304806,127.0,2007,2.12,Adult
1389,2008-2009,All,Trauma,Total,1299765,130.0,2008,2.17,Adult
1808,2004-2005,All,Trauma,Total,1291663,116.0,2004,1.93,Adult
1599,2006-2007,All,Trauma,Total,1285262,122.0,2006,2.03,Adult
1284,2009-2010,All,Trauma,Total,1277121,129.0,2009,2.15,Adult
1913,2003-2004,All,Trauma,Total,1224157,111.0,2003,1.85,Adult
514,2017-2018,Male,Trauma,Total,1101723,132.0,2017,2.20,Adult

In [13]:
print("\nRandom Sample")

display(
    df.sample(
        10,
        random_state=42
    )
)

Random Sample

,fiscal_year,sex,main_problem,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category
889,2013-2014,Female,Pneumonia,Total,53163,228.0,2013,3.80,Adult
1672,2006-2007,Male,Unintentional falls,65+,30555,195.0,2006,3.25,Senior
414,2018-2019,Male,Unintentional falls,Total,315415,156.0,2018,2.60,Adult
1599,2006-2007,All,Trauma,Total,1285262,122.0,2006,2.03,Adult
849,2013-2014,All,Asthma,Total,66072,156.0,2013,2.60,Adult
1658,2006-2007,Male,Pneumonia,Total,34513,206.0,2006,3.43,Adult
926,2013-2014,Male,Influenzal pneumonia,20–44,228,201.0,2013,3.35,Adult
1670,2006-2007,Male,Unintentional falls,20–44,44676,135.0,2006,2.25,Adult
1448,2008-2009,Male,Pneumonia,65+,13472,397.0,2008,6.62,Senior
1216,2010-2011,Female,Unintentional falls,20–44,56950,132.0,2010,2.20,Adult

In [14]:
print("\nRemoving 'All' from Sex...")

df["sex"] = (
    df["sex"]
    .astype(str)
    .str.strip()
    .str.title()
)

df = df[
    df["sex"] != "All"
].copy()

print(df["sex"].value_counts())

Removing 'All' from Sex...
sex
Male      665
Female    664
Name: count, dtype: int64

In [15]:
print("\nRemoving Total Age Group...")

df["age_group"] = (
    df["age_group"]
    .astype(str)
    .str.strip()
    .str.replace("–","-",regex=False)
)

df = df[
    df["age_group"] != "Total"
].copy()

Removing Total Age Group...

In [16]:
age_mapping = {

    "00-04":"0-19",
    "05-09":"0-19",
    "10-14":"0-19",
    "15-19":"0-19",

    "20-24":"20-44",
    "25-29":"20-44",
    "30-34":"20-44",
    "35-39":"20-44",
    "40-44":"20-44",

    "45-49":"45-64",
    "50-54":"45-64",
    "55-59":"45-64",
    "60-64":"45-64",

    "65-69":"65+",
    "70-74":"65+",
    "75-79":"65+",
    "80-84":"65+",
    "85+":"65+"

}

df["age_group"] = (
    df["age_group"]
    .replace(age_mapping)
)

In [17]:
population_mapping = {

    "0-19":"Pediatric & Youth",

    "20-44":"Young Adult",

    "45-64":"Middle Adult",

    "65+":"Older Adult"

}

df["population_category"] = (
    df["age_group"]
    .replace(population_mapping)
)

In [18]:
rename_columns = {

    "median_length_of_stay_min":"median_los_minutes",

    "length_of_stay_hours":"median_los_hours"

}

df.rename(
    columns=rename_columns,
    inplace=True
)

In [19]:
df["median_los_minutes"] = (

    pd.to_numeric(
        df["median_los_minutes"],
        errors="coerce"
    )

    .round()

    .astype(int)

)

df["median_los_hours"] = (

    df["median_los_minutes"]/60

).round(2)

In [20]:
print("\nCleaning Main Problem...")

df["main_problem"] = (

    df["main_problem"]

    .astype(str)

    .str.strip()

    .str.title()

    .str.replace(
        r"\s+",
        " ",
        regex=True
    )

)

Cleaning Main Problem...

In [21]:
df["problem_rank"] = (

    df.groupby("fiscal_year")["ed_visits"]

      .rank(
          method="dense",
          ascending=False
      )

      .astype(int)

)

In [22]:
df["erbi"] = (

    df["ed_visits"]

    *

    df["median_los_minutes"]

)

In [23]:
print("VERIFICATION")
print("="*90)

print("\nSex")

print(df["sex"].value_counts())

print("\nAge Groups")

print(df["age_group"].value_counts())

print("\nPopulation Category")

print(df["population_category"].value_counts())

print("\nTop Problems")

display(
    df["main_problem"]
    .value_counts()
    .head(20)
)

print("\nProblem Rank")

display(
    df[
        [
            "main_problem",
            "problem_rank"
        ]
    ].head(20)
)

print("\nERBI Summary")

display(
    df["erbi"].describe()
)

display(df.head(20))

VERIFICATION
==========================================================================================

Sex
sex
Male      532
Female    531
Name: count, dtype: int64

Age Groups
age_group
20-44    266
45-64    266
65+      266
00-19    265
Name: count, dtype: int64

Population Category
population_category
Young Adult     266
Middle Adult    266
Older Adult     266
00-19           265
Name: count, dtype: int64

Top Problems

main_problem
Asthma                         152
Pneumonia                      152
Influenzal Pneumonia           152
Trauma                         152
Unintentional Falls            152
Motor Vehicle Collisions       152
Acute Myocardial Infarction    151
Name: count, dtype: int64

Problem Rank

                   main_problem  problem_rank
35  Acute Myocardial Infarction            53
36  Acute Myocardial Infarction            46
37  Acute Myocardial Infarction            41
38  Acute Myocardial Infarction            33
40                       Asthma            32
41                       Asthma            29
42                       Asthma            40
43                       Asthma            43
45                    Pneumonia            36
46                    Pneumonia            39
47                    Pneumonia            35
48                    Pneumonia            24
50         Influenzal Pneumonia            50
51         Influenzal Pneumonia            49
52         Influenzal Pneumonia            48
53         Influenzal Pneumonia            50
55                       Trauma             4
56                       Trauma             3
57                       Trauma             7
58                       Trauma             6

ERBI Summary

count    1.063000e+03
mean     6.555322e+06
std      1.013266e+07
min      0.000000e+00
25%      5.664305e+05
50%      1.997352e+06
75%      7.774890e+06
max      5.291770e+07
Name: erbi, dtype: float64

,fiscal_year,sex,main_problem,age_group,ed_visits,median_los_minutes,fiscal_year_start,median_los_hours,age_broad_category,population_category,problem_rank,erbi
35,2021-2022,Female,Acute Myocardial Infarction,00-19,0,216,2021,3.60,Adult,00-19,53,0
36,2021-2022,Female,Acute Myocardial Infarction,20-44,291,450,2021,7.50,Adult,Young Adult,46,130950
37,2021-2022,Female,Acute Myocardial Infarction,45-64,2485,408,2021,6.80,Adult,Middle Adult,41,1013880
38,2021-2022,Female,Acute Myocardial Infarction,65+,6555,498,2021,8.30,Senior,Older Adult,33,3264390
40,2021-2022,Female,Asthma,00-19,7013,222,2021,3.70,Adult,00-19,32,1556886
41,2021-2022,Female,Asthma,20-44,7392,186,2021,3.10,Adult,Young Adult,29,1374912
42,2021-2022,Female,Asthma,45-64,3715,216,2021,3.60,Adult,Middle Adult,40,802440
43,2021-2022,Female,Asthma,65+,2010,276,2021,4.60,Senior,Older Adult,43,554760
45,2021-2022,Female,Pneumonia,00-19,5884,204,2021,3.40,Adult,00-19,36,1200336
46,2021-2022,Female,Pneumonia,20-44,4527,276,2021,4.60,Adult,Young Adult,39,1249452
47,2021-2022,Female,Pneumonia,45-64,6137,324,2021,5.40,Adult,Middle Adult,35,1988388
48,2021-2022,Female,Pneumonia,65+,12619,474,2021,7.90,Senior,Older Adult,24,5981406
50,2021-2022,Female,Influenzal Pneumonia,00-19,8,186,2021,3.10,Adult,00-19,50,1488
51,2021-2022,Female,Influenzal Pneumonia,20-44,9,198,2021,3.30,Adult,Young Adult,49,1782
52,2021-2022,Female,Influenzal Pneumonia,45-64,11,486,2021,8.10,Adult,Middle Adult,48,5346
53,2021-2022,Female,Influenzal Pneumonia,65+,8,345,2021,5.75,Senior,Older Adult,50,2760
55,2021-2022,Female,Trauma,00-19,213633,132,2021,2.20,Adult,00-19,4,28199556
56,2021-2022,Female,Trauma,20-44,263151,144,2021,2.40,Adult,Young Adult,3,37893744
57,2021-2022,Female,Trauma,45-64,186777,156,2021,2.60,Adult,Middle Adult,7,29137212
58,2021-2022,Female,Trauma,65+,188252,240,2021,4.00,Senior,Older Adult,6,45180480

In [24]:
#erbi = ED Visits x Medion LOS

In [25]:
print("\nSorting Dataset...")

df = (
    df.sort_values(
        by=[
            "fiscal_year_start",
            "sex",
            "main_problem",
            "age_group"
        ],
        ascending=[
            False,
            True,
            True,
            True
        ]
    )
    .reset_index(drop=True)
)

print("Dataset Sorted Successfully.")

Sorting Dataset...
Dataset Sorted Successfully.

In [26]:
print("\nReordering Columns...")

final_columns = [

    "fiscal_year",

    "fiscal_year_start",

    "sex",

    "main_problem",

    "age_group",

    "population_category",

    "ed_visits",

    "median_los_minutes",

    "median_los_hours",

    "erbi"

]

df = df[final_columns]

print("Column Order Updated.")

Reordering Columns...
Column Order Updated.

In [27]:
print(f"\nTotal Rows          : {len(df):,}")
print(f"Total Columns       : {len(df.columns)}")

print("\nColumn Names")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

print("\nMemory Usage")
print(f"{df.memory_usage(deep=True).sum()/1024:.2f} KB")

Total Rows          : 1,063
Total Columns       : 10

Column Names
['fiscal_year', 'fiscal_year_start', 'sex', 'main_problem', 'age_group', 'population_category', 'ed_visits', 'median_los_minutes', 'median_los_hours', 'erbi']

Data Types
fiscal_year                str
fiscal_year_start        int64
sex                        str
main_problem               str
age_group                  str
population_category        str
ed_visits                int64
median_los_minutes       int64
median_los_hours       float64
erbi                     int64
dtype: object

Missing Values
fiscal_year            0
fiscal_year_start      0
sex                    0
main_problem           0
age_group              0
population_category    0
ed_visits              0
median_los_minutes     0
median_los_hours       0
erbi                   0
dtype: int64

Duplicate Rows
0

Memory Usage
129.60 KB

In [28]:
print("\nFiscal Years")
print(sorted(df["fiscal_year"].unique(), reverse=True))

print("\nSex Categories")
print(df["sex"].unique())

print("\nAge Groups")
print(df["age_group"].unique())

print("\nPopulation Categories")
print(df["population_category"].unique())

print("\nMain Problems")
print(df["main_problem"].nunique())

Fiscal Years
['2021-2022', '2020-2021', '2019-2020', '2018-2019', '2017-2018', '2016-2017', '2015-2016', '2014-2015', '2013-2014', '2012-2013', '2011-2012', '2010-2011', '2009-2010', '2008-2009', '2007-2008', '2006-2007', '2005-2006', '2004-2005', '2003-2004']

Sex Categories
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

Age Groups
<ArrowStringArray>
['00-19', '20-44', '45-64', '65+']
Length: 4, dtype: str

Population Categories
<ArrowStringArray>
['00-19', 'Young Adult', 'Middle Adult', 'Older Adult']
Length: 4, dtype: str

Main Problems
7

In [29]:
print("\nNumerical Summary")

display(df.describe())

Numerical Summary

,fiscal_year_start,ed_visits,median_los_minutes,median_los_hours,erbi
count,1063.000000,1063.000000,1063.000000,1063.000000,1.063000e+03
mean,2012.005644,44892.645343,203.489182,3.391627,6.555322e+06
std,5.479285,77775.444996,108.372864,1.806221,1.013266e+07
min,2003.000000,0.000000,0.000000,0.000000,0.000000e+00
25%,2007.000000,2484.000000,138.000000,2.300000,5.664305e+05
50%,2012.000000,11437.000000,170.000000,2.830000,1.997352e+06
75%,2017.000000,49328.500000,224.500000,3.740000,7.774890e+06
max,2021.000000,399962.000000,1264.000000,21.070000,5.291770e+07

In [30]:
print("\nTop 20 Main Problems by ED Visits")

display(

    df.groupby("main_problem")["ed_visits"]

      .sum()

      .sort_values(ascending=False)

      .head(20)

)

Top 20 Main Problems by ED Visits

main_problem
Trauma                         31504096
Unintentional Falls            10032213
Motor Vehicle Collisions        2731819
Pneumonia                       1818520
Asthma                          1215647
Acute Myocardial Infarction      402452
Influenzal Pneumonia              16135
Name: ed_visits, dtype: int64

In [32]:
print("\nEstimated Resource Burden Index")

display(

    df["erbi"].describe()

)

Estimated Resource Burden Index

count    1.063000e+03
mean     6.555322e+06
std      1.013266e+07
min      0.000000e+00
25%      5.664305e+05
50%      1.997352e+06
75%      7.774890e+06
max      5.291770e+07
Name: erbi, dtype: float64

In [33]:
print("\nFirst 20 Rows")

display(df.head(20))

print("\nLast 20 Rows")

display(df.tail(20))

print("\nRandom Sample")

display(

    df.sample(

        10,

        random_state=42

    )

)

First 20 Rows

,fiscal_year,fiscal_year_start,sex,main_problem,age_group,population_category,ed_visits,median_los_minutes,median_los_hours,erbi
0,2021-2022,2021,Female,Acute Myocardial Infarction,00-19,00-19,0,216,3.60,0
1,2021-2022,2021,Female,Acute Myocardial Infarction,20-44,Young Adult,291,450,7.50,130950
2,2021-2022,2021,Female,Acute Myocardial Infarction,45-64,Middle Adult,2485,408,6.80,1013880
3,2021-2022,2021,Female,Acute Myocardial Infarction,65+,Older Adult,6555,498,8.30,3264390
4,2021-2022,2021,Female,Asthma,00-19,00-19,7013,222,3.70,1556886
5,2021-2022,2021,Female,Asthma,20-44,Young Adult,7392,186,3.10,1374912
6,2021-2022,2021,Female,Asthma,45-64,Middle Adult,3715,216,3.60,802440
7,2021-2022,2021,Female,Asthma,65+,Older Adult,2010,276,4.60,554760
8,2021-2022,2021,Female,Influenzal Pneumonia,00-19,00-19,8,186,3.10,1488
9,2021-2022,2021,Female,Influenzal Pneumonia,20-44,Young Adult,9,198,3.30,1782
10,2021-2022,2021,Female,Influenzal Pneumonia,45-64,Middle Adult,11,486,8.10,5346
11,2021-2022,2021,Female,Influenzal Pneumonia,65+,Older Adult,8,345,5.75,2760
12,2021-2022,2021,Female,Motor Vehicle Collisions,00-19,00-19,13882,150,2.50,2082300
13,2021-2022,2021,Female,Motor Vehicle Collisions,20-44,Young Adult,27461,174,2.90,4778214
14,2021-2022,2021,Female,Motor Vehicle Collisions,45-64,Middle Adult,14557,192,3.20,2794944
15,2021-2022,2021,Female,Motor Vehicle Collisions,65+,Older Adult,6199,228,3.80,1413372
16,2021-2022,2021,Female,Pneumonia,00-19,00-19,5884,204,3.40,1200336
17,2021-2022,2021,Female,Pneumonia,20-44,Young Adult,4527,276,4.60,1249452
18,2021-2022,2021,Female,Pneumonia,45-64,Middle Adult,6137,324,5.40,1988388
19,2021-2022,2021,Female,Pneumonia,65+,Older Adult,12619,474,7.90,5981406

Last 20 Rows

,fiscal_year,fiscal_year_start,sex,main_problem,age_group,population_category,ed_visits,median_los_minutes,median_los_hours,erbi
1043,2003-2004,2003,Male,Influenzal Pneumonia,00-19,00-19,21,87,1.45,1827
1044,2003-2004,2003,Male,Influenzal Pneumonia,20-44,Young Adult,21,153,2.55,3213
1045,2003-2004,2003,Male,Influenzal Pneumonia,45-64,Middle Adult,15,112,1.87,1680
1046,2003-2004,2003,Male,Influenzal Pneumonia,65+,Older Adult,21,184,3.07,3864
1047,2003-2004,2003,Male,Motor Vehicle Collisions,00-19,00-19,22377,115,1.92,2573355
1048,2003-2004,2003,Male,Motor Vehicle Collisions,20-44,Young Adult,28964,135,2.25,3910140
1049,2003-2004,2003,Male,Motor Vehicle Collisions,45-64,Middle Adult,10943,145,2.42,1586735
1050,2003-2004,2003,Male,Motor Vehicle Collisions,65+,Older Adult,3640,160,2.67,582400
1051,2003-2004,2003,Male,Pneumonia,00-19,00-19,10055,155,2.58,1558525
1052,2003-2004,2003,Male,Pneumonia,20-44,Young Adult,5050,173,2.88,873650
1053,2003-2004,2003,Male,Pneumonia,45-64,Middle Adult,5327,207,3.45,1102689
1054,2003-2004,2003,Male,Pneumonia,65+,Older Adult,12119,270,4.50,3272130
1055,2003-2004,2003,Male,Trauma,00-19,00-19,251651,100,1.67,25165100
1056,2003-2004,2003,Male,Trauma,20-44,Young Adult,303230,109,1.82,33052070
1057,2003-2004,2003,Male,Trauma,45-64,Middle Adult,121150,114,1.90,13811100
1058,2003-2004,2003,Male,Trauma,65+,Older Adult,51563,147,2.45,7579761
1059,2003-2004,2003,Male,Unintentional Falls,00-19,00-19,72683,107,1.78,7777081
1060,2003-2004,2003,Male,Unintentional Falls,20-44,Young Adult,44930,123,2.05,5526390
1061,2003-2004,2003,Male,Unintentional Falls,45-64,Middle Adult,28700,140,2.33,4018000
1062,2003-2004,2003,Male,Unintentional Falls,65+,Older Adult,26121,184,3.07,4806264

Random Sample

,fiscal_year,fiscal_year_start,sex,main_problem,age_group,population_category,ed_visits,median_los_minutes,median_los_hours,erbi
31,2021-2022,2021,Male,Acute Myocardial Infarction,65+,Older Adult,9065,396,6.60,3589740
413,2014-2015,2014,Female,Trauma,20-44,Young Adult,255279,120,2.00,30633480
536,2012-2013,2012,Male,Asthma,00-19,00-19,20280,156,2.60,3163680
745,2008-2009,2008,Female,Pneumonia,20-44,Young Adult,5812,180,3.00,1046160
877,2006-2007,2006,Male,Influenzal Pneumonia,45-64,Middle Adult,12,202,3.37,2424
628,2010-2011,2010,Female,Motor Vehicle Collisions,00-19,00-19,16182,122,2.03,1974204
952,2004-2005,2004,Female,Acute Myocardial Infarction,20-44,Young Adult,123,148,2.47,18204
722,2009-2010,2009,Male,Trauma,45-64,Middle Adult,144190,130,2.17,18744700
86,2020-2021,2020,Male,Acute Myocardial Infarction,45-64,Middle Adult,6840,264,4.40,1805760
1033,2003-2004,2003,Female,Unintentional Falls,45-64,Middle Adult,34428,140,2.33,4819920

In [37]:
population_mapping = {

    "00-19": "Pediatric & Youth",

    "20-44": "Young Adult",

    "45-64": "Middle Adult",

    "65+": "Older Adult"

}

df["population_category"] = df["age_group"].map(population_mapping)

In [38]:
# Standardize age_group
df["age_group"] = (
    df["age_group"]
    .astype(str)
    .str.strip()
    .str.replace("00-19", "0-19")
)

# Create population category
population_mapping = {

    "0-19": "Pediatric & Youth",

    "20-44": "Young Adult",

    "45-64": "Middle Adult",

    "65+": "Older Adult"

}

df["population_category"] = df["age_group"].map(population_mapping)

In [39]:
print(df["age_group"].unique())
print(df["population_category"].unique())

<ArrowStringArray>
['0-19', '20-44', '45-64', '65+']
Length: 4, dtype: str
<ArrowStringArray>
['Pediatric & Youth', 'Young Adult', 'Middle Adult', 'Older Adult']
Length: 4, dtype: str

In [40]:
print("\nSaving Dataset...")

df.to_csv(

    OUTPUT_FILE,

    index=False

)

print("Dataset Saved Successfully.")

print("\nSaved Location")

print(OUTPUT_FILE)

Saving Dataset...
Dataset Saved Successfully.

Saved Location
C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\Explorer Dataset\Main_Problems.csv