In [1]:
from IPython.display import display
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [2]:
INPUT_FILE = Path(
    r"C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\optimized\Visit_Disposition.csv"
)

OUTPUT_FOLDER = Path(
    r"C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\Explorer Dataset"
)

OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

OUTPUT_FILE = OUTPUT_FOLDER / "Visit_Disposition.csv"

In [4]:
df = pd.read_csv(INPUT_FILE)

print("VISIT DISPOSITION DATASET LOADED SUCCESSFULLY")

VISIT DISPOSITION DATASET LOADED SUCCESSFULLY

In [5]:
print("\nFIRST 10 ROWS")
display(df.head(10))

print("\nLAST 10 ROWS")
display(df.tail(10))

FIRST 10 ROWS

,fiscal_year,sex,visit_disposition,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category,is_admitted
0,2021-2022,All,Discharged home,00–19,2276713,156.0,2021,2.6,Adult,0
1,2021-2022,All,Discharged home,20–44,3835086,186.0,2021,3.1,Adult,0
2,2021-2022,All,Discharged home,45–64,2666691,204.0,2021,3.4,Adult,0
3,2021-2022,All,Discharged home,65+,2259147,240.0,2021,4.0,Senior,0
4,2021-2022,All,Discharged home,Total,11038792,192.0,2021,3.2,Adult,0
5,2021-2022,All,Not seen or left,00–19,196851,150.0,2021,2.5,Adult,0
6,2021-2022,All,Not seen or left,20–44,419581,174.0,2021,2.9,Adult,0
7,2021-2022,All,Not seen or left,45–64,218536,180.0,2021,3.0,Adult,0
8,2021-2022,All,Not seen or left,65+,128161,180.0,2021,3.0,Senior,0
9,2021-2022,All,Not seen or left,Total,963637,168.0,2021,2.8,Adult,0

LAST 10 ROWS

,fiscal_year,sex,visit_disposition,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category,is_admitted
1745,2003-2004,Male,Intra-facility transfer,00–19,2136,131.5,2003,2.19,Adult,0
1746,2003-2004,Male,Intra-facility transfer,20–44,3620,161.0,2003,2.68,Adult,0
1747,2003-2004,Male,Intra-facility transfer,45–64,2507,180.0,2003,3.00,Adult,0
1748,2003-2004,Male,Intra-facility transfer,65+,1692,203.0,2003,3.38,Senior,0
1749,2003-2004,Male,Intra-facility transfer,Total,9955,165.0,2003,2.75,Adult,0
1750,2003-2004,Male,Unknown,00–19,6371,55.0,2003,0.92,Adult,0
1751,2003-2004,Male,Unknown,20–44,6254,58.0,2003,0.97,Adult,0
1752,2003-2004,Male,Unknown,45–64,4659,64.0,2003,1.07,Adult,0
1753,2003-2004,Male,Unknown,65+,3932,83.0,2003,1.38,Senior,0
1754,2003-2004,Male,Unknown,Total,21216,61.0,2003,1.02,Adult,0

In [6]:
print("\nDataset Shape")
print(df.shape)

print("\nColumn Names")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

Dataset Shape
(1755, 10)

Column Names
['fiscal_year', 'sex', 'visit_disposition', 'age_group', 'ed_visits', 'median_length_of_stay_min', 'fiscal_year_start', 'length_of_stay_hours', 'age_broad_category', 'is_admitted']

Data Types
fiscal_year                      str
sex                              str
visit_disposition                str
age_group                        str
ed_visits                      int64
median_length_of_stay_min    float64
fiscal_year_start              int64
length_of_stay_hours         float64
age_broad_category               str
is_admitted                    int64
dtype: object

In [7]:
print("\nMissing Values")

display(df.isnull().sum())

Missing Values

fiscal_year                  0
sex                          0
visit_disposition            0
age_group                    0
ed_visits                    0
median_length_of_stay_min    0
fiscal_year_start            0
length_of_stay_hours         0
age_broad_category           0
is_admitted                  0
dtype: int64

In [8]:
print("\nDuplicate Rows")

print(df.duplicated().sum())

Duplicate Rows
0

In [9]:
print("\nSummary Statistics")

display(df.describe(include="all"))

Summary Statistics

,fiscal_year,sex,visit_disposition,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category,is_admitted
count,1755,1755,1755,1755,1.755000e+03,1755.000000,1755.000000,1755.000000,1755,1755.000000
unique,19,3,7,5,NaN,NaN,NaN,NaN,2,NaN
top,2008-2009,All,Discharged home,00–19,NaN,NaN,NaN,NaN,Adult,NaN
freq,105,585,285,351,NaN,NaN,NaN,NaN,1404,NaN
mean,NaN,NaN,NaN,NaN,4.006274e+05,209.357550,2011.820513,3.489276,NaN,0.162393
std,NaN,NaN,NaN,NaN,1.102065e+06,163.666043,5.531008,2.727739,NaN,0.368916
min,NaN,NaN,NaN,NaN,8.000000e+01,20.000000,2003.000000,0.330000,NaN,0.000000
25%,NaN,NaN,NaN,NaN,6.260500e+03,119.000000,2007.000000,1.980000,NaN,0.000000
50%,NaN,NaN,NaN,NaN,3.699300e+04,168.000000,2012.000000,2.800000,NaN,0.000000
75%,NaN,NaN,NaN,NaN,2.202800e+05,240.000000,2017.000000,4.000000,NaN,0.000000
max,NaN,NaN,NaN,NaN,1.197070e+07,966.000000,2021.000000,16.100000,NaN,1.000000

In [10]:
print("\nFiscal Years")
display(df["fiscal_year"].value_counts())

print("\nSex")
display(df["sex"].value_counts())

print("\nVisit Disposition")
display(df["visit_disposition"].value_counts())

print("\nAge Groups")
display(df["age_group"].value_counts())

print("\nAdmission Flag")
display(df["is_admitted"].value_counts())

Fiscal Years

fiscal_year
2008-2009    105
2004-2005    105
2003-2004    105
2021-2022     90
2020-2021     90
2019-2020     90
2018-2019     90
2017-2018     90
2016-2017     90
2015-2016     90
2014-2015     90
2013-2014     90
2012-2013     90
2011-2012     90
2010-2011     90
2009-2010     90
2007-2008     90
2006-2007     90
2005-2006     90
Name: count, dtype: int64

Sex

sex
All       585
Female    585
Male      585
Name: count, dtype: int64

Visit Disposition

visit_disposition
Discharged home            285
Not seen or left           285
Admitted                   285
Transferred                285
Death                      285
Intra-facility transfer    285
Unknown                     45
Name: count, dtype: int64

Age Groups

age_group
00–19    351
20–44    351
45–64    351
65+      351
Total    351
Name: count, dtype: int64

Admission Flag

is_admitted
0    1470
1     285
Name: count, dtype: int64

In [11]:
print("\nED Visits")

display(df["ed_visits"].describe())

print("\nMedian Length of Stay")

display(df["median_length_of_stay_min"].describe())

print("\nLength of Stay (Hours)")

display(df["length_of_stay_hours"].describe())

ED Visits

count    1.755000e+03
mean     4.006274e+05
std      1.102065e+06
min      8.000000e+01
25%      6.260500e+03
50%      3.699300e+04
75%      2.202800e+05
max      1.197070e+07
Name: ed_visits, dtype: float64

Median Length of Stay

count    1755.000000
mean      209.357550
std       163.666043
min        20.000000
25%       119.000000
50%       168.000000
75%       240.000000
max       966.000000
Name: median_length_of_stay_min, dtype: float64

Length of Stay (Hours)

count    1755.000000
mean        3.489276
std         2.727739
min         0.330000
25%         1.980000
50%         2.800000
75%         4.000000
max        16.100000
Name: length_of_stay_hours, dtype: float64

In [12]:
print("DATA QUALITY REPORT")
print("-"*90)

print(f"Rows               : {df.shape[0]:,}")
print(f"Columns            : {df.shape[1]}")
print(f"Duplicate Rows     : {df.duplicated().sum()}")
print(f"Missing Cells      : {df.isnull().sum().sum()}")

print("\nMissing Values By Column")

display(df.isnull().sum())

DATA QUALITY REPORT
------------------------------------------------------------------------------------------
Rows               : 1,755
Columns            : 10
Duplicate Rows     : 0
Missing Cells      : 0

Missing Values By Column

fiscal_year                  0
sex                          0
visit_disposition            0
age_group                    0
ed_visits                    0
median_length_of_stay_min    0
fiscal_year_start            0
length_of_stay_hours         0
age_broad_category           0
is_admitted                  0
dtype: int64

In [13]:
print("\nVisit Disposition Frequency")

display(
    df["visit_disposition"]
      .value_counts()
)

Visit Disposition Frequency

visit_disposition
Discharged home            285
Not seen or left           285
Admitted                   285
Transferred                285
Death                      285
Intra-facility transfer    285
Unknown                     45
Name: count, dtype: int64

In [14]:
print("\nTop 20 Records by ED Visits")

display(
    df.nlargest(
        20,
        "ed_visits"
    )
)

Top 20 Records by ED Visits

,fiscal_year,sex,visit_disposition,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category,is_admitted
274,2018-2019,All,Discharged home,Total,11970703,174.0,2018,2.90,Adult,0
184,2019-2020,All,Discharged home,Total,11842440,180.0,2019,3.00,Adult,0
4,2021-2022,All,Discharged home,Total,11038792,192.0,2021,3.20,Adult,0
364,2017-2018,All,Discharged home,Total,9574065,156.0,2017,2.60,Adult,0
454,2016-2017,All,Discharged home,Total,9394015,150.0,2016,2.50,Adult,0
544,2015-2016,All,Discharged home,Total,9343905,144.0,2015,2.40,Adult,0
94,2020-2021,All,Discharged home,Total,9286561,168.0,2020,2.80,Adult,0
634,2014-2015,All,Discharged home,Total,9154262,144.0,2014,2.40,Adult,0
724,2013-2014,All,Discharged home,Total,8760827,138.0,2013,2.30,Adult,0
814,2012-2013,All,Discharged home,Total,8490280,136.0,2012,2.27,Adult,0
904,2011-2012,All,Discharged home,Total,7687630,135.0,2011,2.25,Adult,0
994,2010-2011,All,Discharged home,Total,6949540,133.0,2010,2.22,Adult,0
304,2018-2019,Female,Discharged home,Total,6290628,180.0,2018,3.00,Adult,0
214,2019-2020,Female,Discharged home,Total,6205357,186.0,2019,3.10,Adult,0
34,2021-2022,Female,Discharged home,Total,5770431,204.0,2021,3.40,Adult,0
334,2018-2019,Male,Discharged home,Total,5678602,168.0,2018,2.80,Adult,0
244,2019-2020,Male,Discharged home,Total,5635732,174.0,2019,2.90,Adult,0
64,2021-2022,Male,Discharged home,Total,5265669,186.0,2021,3.10,Adult,0
394,2017-2018,Female,Discharged home,Total,5018183,162.0,2017,2.70,Adult,0
484,2016-2017,Female,Discharged home,Total,4926637,156.0,2016,2.60,Adult,0

In [15]:
print("\nRandom Sample")

display(
    df.sample(
        10,
        random_state=42
    )
)

Random Sample

,fiscal_year,sex,visit_disposition,age_group,ed_visits,median_length_of_stay_min,fiscal_year_start,length_of_stay_hours,age_broad_category,is_admitted
322,2018-2019,Female,Death,45–64,1158,60.0,2018,1.00,Adult,0
408,2017-2018,Female,Transferred,65+,22557,300.0,2017,5.00,Senior,0
405,2017-2018,Female,Transferred,00–19,11773,240.0,2017,4.00,Adult,0
462,2016-2017,All,Admitted,45–64,264284,630.0,2016,10.50,Adult,1
1137,2009-2010,Female,Intra-facility transfer,45–64,1717,201.0,2009,3.35,Adult,0
1244,2008-2009,Male,Discharged home,Total,2228092,135.0,2008,2.25,Adult,0
1205,2008-2009,Female,Discharged home,00–19,575901,120.0,2008,2.00,Adult,0
799,2013-2014,Male,Transferred,Total,64505,234.0,2013,3.90,Adult,0
1295,2007-2008,All,Death,00–19,242,25.0,2007,0.42,Adult,0
1151,2009-2010,Male,Admitted,20–44,41069,521.0,2009,8.68,Adult,1

In [16]:
df["sex"] = (
    df["sex"]
    .astype(str)
    .str.strip()
    .str.title()
)

df = df[df["sex"] != "All"].copy()

In [17]:
df["age_group"] = (
    df["age_group"]
    .astype(str)
    .str.strip()
    .str.replace("–", "-", regex=False)
)

df = df[df["age_group"] != "Total"].copy()

In [18]:
age_mapping = {

    "00-04":"0-19",
    "05-09":"0-19",
    "10-14":"0-19",
    "15-19":"0-19",

    "20-24":"20-44",
    "25-29":"20-44",
    "30-34":"20-44",
    "35-39":"20-44",
    "40-44":"20-44",

    "45-49":"45-64",
    "50-54":"45-64",
    "55-59":"45-64",
    "60-64":"45-64",

    "65-69":"65+",
    "70-74":"65+",
    "75-79":"65+",
    "80-84":"65+",
    "85+":"65+"

}

In [19]:
df["age_group"] = df["age_group"].replace(age_mapping)

In [20]:
population_mapping = {

    "0-19":"Pediatric & Youth",

    "20-44":"Young Adult",

    "45-64":"Middle Adult",

    "65+":"Older Adult"

}

df["population_category"] = df["age_group"].map(population_mapping)

In [21]:
df.rename(
    columns={
        "median_length_of_stay_min":"median_los_minutes",
        "length_of_stay_hours":"median_los_hours",
        "is_admitted":"admission_flag"
    },
    inplace=True
)

In [22]:
df["visit_disposition"] = (
    df["visit_disposition"]
    .astype(str)
    .str.strip()
    .replace({

        "Discharged home":"Discharged",

        "Not seen or left":"Left Without Being Seen",

        "Transferred":"Transferred",

        "Intra-facility transfer":"Intra-Facility Transfer",

        "Admitted":"Admitted",

        "Death":"Death",

        "Unknown":"Unknown"

    })
)

In [23]:
df["admission_status"] = df["admission_flag"].map({

    0:"Not Admitted",

    1:"Admitted"

})

In [24]:
df["median_los_minutes"] = (
    pd.to_numeric(
        df["median_los_minutes"],
        errors="coerce"
    )
    .round()
    .astype(int)
)

df["median_los_hours"] = (
    df["median_los_minutes"]/60
).round(2)

In [25]:
df["ed_visits"] = (
    pd.to_numeric(
        df["ed_visits"],
        errors="coerce"
    )
    .fillna(0)
    .astype(int)
)

In [26]:
df["erbi"] = (
    df["ed_visits"] *
    df["median_los_minutes"]
)

In [27]:
print("\nSex")
print(df["sex"].value_counts())

print("\nAge Groups")
print(df["age_group"].value_counts())

print("\nPopulation Categories")
print(df["population_category"].value_counts())

print("\nVisit Disposition")
print(df["visit_disposition"].value_counts())

print("\nAdmission Status")
print(df["admission_status"].value_counts())

display(df.head(20))

Sex
sex
Female    468
Male      468
Name: count, dtype: int64

Age Groups
age_group
00-19    234
20-44    234
45-64    234
65+      234
Name: count, dtype: int64

Population Categories
population_category
Young Adult     234
Middle Adult    234
Older Adult     234
Name: count, dtype: int64

Visit Disposition
visit_disposition
Discharged                 152
Left Without Being Seen    152
Admitted                   152
Transferred                152
Death                      152
Intra-Facility Transfer    152
Unknown                     24
Name: count, dtype: int64

Admission Status
admission_status
Not Admitted    784
Admitted        152
Name: count, dtype: int64

,fiscal_year,sex,visit_disposition,age_group,ed_visits,median_los_minutes,fiscal_year_start,median_los_hours,age_broad_category,admission_flag,population_category,admission_status,erbi
30,2021-2022,Female,Discharged,00-19,1111383,162,2021,2.7,Adult,0,NaN,Not Admitted,180044046
31,2021-2022,Female,Discharged,20-44,2099271,198,2021,3.3,Adult,0,Young Adult,Not Admitted,415655658
32,2021-2022,Female,Discharged,45-64,1362105,204,2021,3.4,Adult,0,Middle Adult,Not Admitted,277869420
33,2021-2022,Female,Discharged,65+,1197410,246,2021,4.1,Senior,0,Older Adult,Not Admitted,294562860
35,2021-2022,Female,Left Without Being Seen,00-19,98886,150,2021,2.5,Adult,0,NaN,Not Admitted,14832900
36,2021-2022,Female,Left Without Being Seen,20-44,213981,180,2021,3.0,Adult,0,Young Adult,Not Admitted,38516580
37,2021-2022,Female,Left Without Being Seen,45-64,99494,180,2021,3.0,Adult,0,Middle Adult,Not Admitted,17908920
38,2021-2022,Female,Left Without Being Seen,65+,62794,180,2021,3.0,Senior,0,Older Adult,Not Admitted,11302920
40,2021-2022,Female,Admitted,00-19,61448,450,2021,7.5,Adult,1,NaN,Admitted,27651600
41,2021-2022,Female,Admitted,20-44,135970,702,2021,11.7,Adult,1,Young Adult,Admitted,95450940
42,2021-2022,Female,Admitted,45-64,154636,792,2021,13.2,Adult,1,Middle Adult,Admitted,122471712
43,2021-2022,Female,Admitted,65+,423379,966,2021,16.1,Senior,1,Older Adult,Admitted,408984114
45,2021-2022,Female,Transferred,00-19,18833,288,2021,4.8,Adult,0,NaN,Not Admitted,5423904
46,2021-2022,Female,Transferred,20-44,39251,330,2021,5.5,Adult,0,Young Adult,Not Admitted,12952830
47,2021-2022,Female,Transferred,45-64,31707,360,2021,6.0,Adult,0,Middle Adult,Not Admitted,11414520
48,2021-2022,Female,Transferred,65+,91621,384,2021,6.4,Senior,0,Older Adult,Not Admitted,35182464
50,2021-2022,Female,Death,00-19,176,36,2021,0.6,Adult,0,NaN,Not Admitted,6336
51,2021-2022,Female,Death,20-44,452,42,2021,0.7,Adult,0,Young Adult,Not Admitted,18984
52,2021-2022,Female,Death,45-64,1144,72,2021,1.2,Adult,0,Middle Adult,Not Admitted,82368
53,2021-2022,Female,Death,65+,5141,150,2021,2.5,Senior,0,Older Adult,Not Admitted,771150

In [28]:
df = (
    df.sort_values(
        by=[
            "fiscal_year_start",
            "visit_disposition",
            "sex",
            "age_group"
        ],
        ascending=[
            False,
            True,
            True,
            True
        ]
    )
    .reset_index(drop=True)
)

print("Dataset Sorted Successfully.")

Dataset Sorted Successfully.

In [29]:
final_columns = [

    "fiscal_year",

    "fiscal_year_start",

    "sex",

    "visit_disposition",

    "admission_flag",

    "admission_status",

    "age_group",

    "population_category",

    "ed_visits",

    "median_los_minutes",

    "median_los_hours",

    "erbi"

]

df = df[final_columns]
print("Column Order Updated.")

Column Order Updated.

In [30]:
print(f"\nTotal Rows          : {len(df):,}")
print(f"Total Columns       : {len(df.columns)}")

print("\nColumn Names")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

print("\nMemory Usage")
print(f"{df.memory_usage(deep=True).sum()/1024:.2f} KB")

Total Rows          : 936
Total Columns       : 12

Column Names
['fiscal_year', 'fiscal_year_start', 'sex', 'visit_disposition', 'admission_flag', 'admission_status', 'age_group', 'population_category', 'ed_visits', 'median_los_minutes', 'median_los_hours', 'erbi']

Data Types
fiscal_year                str
fiscal_year_start        int64
sex                        str
visit_disposition          str
admission_flag           int64
admission_status           str
age_group                  str
population_category        str
ed_visits                int64
median_los_minutes       int64
median_los_hours       float64
erbi                     int64
dtype: object

Missing Values
fiscal_year              0
fiscal_year_start        0
sex                      0
visit_disposition        0
admission_flag           0
admission_status         0
age_group                0
population_category    234
ed_visits                0
median_los_minutes       0
median_los_hours         0
erbi                     0
dtype: int64

Duplicate Rows
0

Memory Usage
135.66 KB

In [31]:
print("\nFiscal Years")
print(sorted(df["fiscal_year"].unique(), reverse=True))

print("\nSex Categories")
print(df["sex"].unique())

print("\nVisit Disposition")
print(df["visit_disposition"].unique())

print("\nAdmission Status")
print(df["admission_status"].unique())

print("\nAge Groups")
print(df["age_group"].unique())

print("\nPopulation Categories")
print(df["population_category"].unique())

Fiscal Years
['2021-2022', '2020-2021', '2019-2020', '2018-2019', '2017-2018', '2016-2017', '2015-2016', '2014-2015', '2013-2014', '2012-2013', '2011-2012', '2010-2011', '2009-2010', '2008-2009', '2007-2008', '2006-2007', '2005-2006', '2004-2005', '2003-2004']

Sex Categories
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

Visit Disposition
<ArrowStringArray>
[               'Admitted',                   'Death',
              'Discharged', 'Intra-Facility Transfer',
 'Left Without Being Seen',             'Transferred',
                 'Unknown']
Length: 7, dtype: str

Admission Status
<ArrowStringArray>
['Admitted', 'Not Admitted']
Length: 2, dtype: str

Age Groups
<ArrowStringArray>
['00-19', '20-44', '45-64', '65+']
Length: 4, dtype: str

Population Categories
<ArrowStringArray>
[nan, 'Young Adult', 'Middle Adult', 'Older Adult']
Length: 4, dtype: str

In [32]:
print("\nNumerical Summary")

display(df.describe())

Numerical Summary

,fiscal_year_start,admission_flag,ed_visits,median_los_minutes,median_los_hours,erbi
count,936.000000,936.000000,9.360000e+02,936.000000,936.000000,9.360000e+02
mean,2011.820513,0.162393,1.877809e+05,207.879274,3.464615,3.790358e+07
std,5.532388,0.369008,3.822876e+05,162.566177,2.709473,7.126332e+07
min,2003.000000,0.000000,8.000000e+01,20.000000,0.330000,2.500000e+03
25%,2007.000000,0.000000,3.712000e+03,115.750000,1.927500,5.660915e+05
50%,2012.000000,0.000000,2.184850e+04,168.000000,2.800000,3.927710e+06
75%,2017.000000,0.000000,1.083555e+05,240.000000,4.000000,3.733275e+07
max,2021.000000,1.000000,2.206226e+06,966.000000,16.100000,4.156557e+08

In [33]:
print("\nVisit Disposition Summary")

display(
    df.groupby("visit_disposition")["ed_visits"]
      .sum()
      .sort_values(ascending=False)
)

Visit Disposition Summary

visit_disposition
Discharged                 145245540
Admitted                    18004220
Left Without Being Seen      8492360
Transferred                  2786266
Intra-Facility Transfer       909384
Death                         182003
Unknown                       143171
Name: ed_visits, dtype: int64

In [34]:
print("\nEstimated Resource Burden Index")

display(df["erbi"].describe())

Estimated Resource Burden Index

count    9.360000e+02
mean     3.790358e+07
std      7.126332e+07
min      2.500000e+03
25%      5.660915e+05
50%      3.927710e+06
75%      3.733275e+07
max      4.156557e+08
Name: erbi, dtype: float64

In [35]:
print("\nFirst 20 Rows")
display(df.head(20))

print("\nLast 20 Rows")
display(df.tail(20))

print("\nRandom Sample")
display(df.sample(10, random_state=42))

First 20 Rows

,fiscal_year,fiscal_year_start,sex,visit_disposition,admission_flag,admission_status,age_group,population_category,ed_visits,median_los_minutes,median_los_hours,erbi
0,2021-2022,2021,Female,Admitted,1,Admitted,00-19,NaN,61448,450,7.5,27651600
1,2021-2022,2021,Female,Admitted,1,Admitted,20-44,Young Adult,135970,702,11.7,95450940
2,2021-2022,2021,Female,Admitted,1,Admitted,45-64,Middle Adult,154636,792,13.2,122471712
3,2021-2022,2021,Female,Admitted,1,Admitted,65+,Older Adult,423379,966,16.1,408984114
4,2021-2022,2021,Male,Admitted,1,Admitted,00-19,NaN,61089,420,7.0,25657380
5,2021-2022,2021,Male,Admitted,1,Admitted,20-44,Young Adult,135841,720,12.0,97805520
6,2021-2022,2021,Male,Admitted,1,Admitted,45-64,Middle Adult,197560,762,12.7,150540720
7,2021-2022,2021,Male,Admitted,1,Admitted,65+,Older Adult,403171,906,15.1,365272926
8,2021-2022,2021,Female,Death,0,Not Admitted,00-19,NaN,176,36,0.6,6336
9,2021-2022,2021,Female,Death,0,Not Admitted,20-44,Young Adult,452,42,0.7,18984
10,2021-2022,2021,Female,Death,0,Not Admitted,45-64,Middle Adult,1144,72,1.2,82368
11,2021-2022,2021,Female,Death,0,Not Admitted,65+,Older Adult,5141,150,2.5,771150
12,2021-2022,2021,Male,Death,0,Not Admitted,00-19,NaN,268,42,0.7,11256
13,2021-2022,2021,Male,Death,0,Not Admitted,20-44,Young Adult,1209,36,0.6,43524
14,2021-2022,2021,Male,Death,0,Not Admitted,45-64,Middle Adult,2866,54,0.9,154764
15,2021-2022,2021,Male,Death,0,Not Admitted,65+,Older Adult,7162,108,1.8,773496
16,2021-2022,2021,Female,Discharged,0,Not Admitted,00-19,NaN,1111383,162,2.7,180044046
17,2021-2022,2021,Female,Discharged,0,Not Admitted,20-44,Young Adult,2099271,198,3.3,415655658
18,2021-2022,2021,Female,Discharged,0,Not Admitted,45-64,Middle Adult,1362105,204,3.4,277869420
19,2021-2022,2021,Female,Discharged,0,Not Admitted,65+,Older Adult,1197410,246,4.1,294562860

Last 20 Rows

,fiscal_year,fiscal_year_start,sex,visit_disposition,admission_flag,admission_status,age_group,population_category,ed_visits,median_los_minutes,median_los_hours,erbi
916,2003-2004,2003,Male,Left Without Being Seen,0,Not Admitted,00-19,NaN,27409,98,1.63,2686082
917,2003-2004,2003,Male,Left Without Being Seen,0,Not Admitted,20-44,Young Adult,40011,115,1.92,4601265
918,2003-2004,2003,Male,Left Without Being Seen,0,Not Admitted,45-64,Middle Adult,17968,116,1.93,2084288
919,2003-2004,2003,Male,Left Without Being Seen,0,Not Admitted,65+,Older Adult,7185,114,1.90,819090
920,2003-2004,2003,Female,Transferred,0,Not Admitted,00-19,NaN,4082,171,2.85,698022
921,2003-2004,2003,Female,Transferred,0,Not Admitted,20-44,Young Adult,5756,210,3.50,1208760
922,2003-2004,2003,Female,Transferred,0,Not Admitted,45-64,Middle Adult,3916,246,4.10,963336
923,2003-2004,2003,Female,Transferred,0,Not Admitted,65+,Older Adult,5621,265,4.42,1489565
924,2003-2004,2003,Male,Transferred,0,Not Admitted,00-19,NaN,5571,164,2.73,913644
925,2003-2004,2003,Male,Transferred,0,Not Admitted,20-44,Young Adult,6687,207,3.45,1384209
926,2003-2004,2003,Male,Transferred,0,Not Admitted,45-64,Middle Adult,5617,218,3.63,1224506
927,2003-2004,2003,Male,Transferred,0,Not Admitted,65+,Older Adult,5131,247,4.12,1267357
928,2003-2004,2003,Female,Unknown,0,Not Admitted,00-19,NaN,6827,54,0.90,368658
929,2003-2004,2003,Female,Unknown,0,Not Admitted,20-44,Young Adult,7229,60,1.00,433740
930,2003-2004,2003,Female,Unknown,0,Not Admitted,45-64,Middle Adult,4832,66,1.10,318912
931,2003-2004,2003,Female,Unknown,0,Not Admitted,65+,Older Adult,4506,90,1.50,405540
932,2003-2004,2003,Male,Unknown,0,Not Admitted,00-19,NaN,6371,55,0.92,350405
933,2003-2004,2003,Male,Unknown,0,Not Admitted,20-44,Young Adult,6254,58,0.97,362732
934,2003-2004,2003,Male,Unknown,0,Not Admitted,45-64,Middle Adult,4659,64,1.07,298176
935,2003-2004,2003,Male,Unknown,0,Not Admitted,65+,Older Adult,3932,83,1.38,326356

Random Sample

,fiscal_year,fiscal_year_start,sex,visit_disposition,admission_flag,admission_status,age_group,population_category,ed_visits,median_los_minutes,median_los_hours,erbi
321,2015-2016,2015,Female,Left Without Being Seen,0,Not Admitted,20-44,Young Adult,103396,132,2.20,13648272
70,2020-2021,2020,Male,Discharged,0,Not Admitted,45-64,Middle Adult,1201166,168,2.80,201795888
209,2017-2018,2017,Female,Discharged,0,Not Admitted,20-44,Young Adult,1765199,162,2.70,285962238
656,2008-2009,2008,Female,Left Without Being Seen,0,Not Admitted,00-19,NaN,36147,122,2.03,4409934
685,2007-2008,2007,Male,Admitted,1,Admitted,20-44,Young Adult,42962,455,7.58,19547710
96,2019-2020,2019,Female,Admitted,1,Admitted,00-19,NaN,66051,414,6.90,27345114
468,2012-2013,2012,Male,Left Without Being Seen,0,Not Admitted,00-19,NaN,49130,106,1.77,5207780
86,2020-2021,2020,Male,Left Without Being Seen,0,Not Admitted,45-64,Middle Adult,75767,144,2.40,10910448
532,2010-2011,2010,Male,Admitted,1,Admitted,00-19,NaN,41914,353,5.88,14795642
327,2015-2016,2015,Male,Left Without Being Seen,0,Not Admitted,65+,Older Adult,22859,138,2.30,3154542

In [37]:
# Standardize age groups first (if needed)
df["age_group"] = (
    df["age_group"]
    .astype(str)
    .str.strip()
    .str.replace("00-19", "0-19", regex=False)
)

# Population category mapping
population_mapping = {
    "0-19": "Pediatric & Youth",
    "20-44": "Young Adult",
    "45-64": "Middle Adult",
    "65+": "Older Adult"
}

df["population_category"] = df["age_group"].map(population_mapping)

# Verify
print(df[["age_group", "population_category"]].drop_duplicates().sort_values("age_group"))

  age_group population_category
0      0-19   Pediatric & Youth
1     20-44         Young Adult
2     45-64        Middle Adult
3       65+         Older Adult

In [38]:
print("\nSaving Dataset...")

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("Dataset Saved Successfully.")

print("\nSaved Location")
print(OUTPUT_FILE)

Saving Dataset...
Dataset Saved Successfully.

Saved Location
C:\Users\bhara\OneDrive\Desktop\DAMO-699-Capstone-Project-Unofficial-\DAMO-699-Capstone-Project-Unofficial-\data\Explorer Dataset\Visit_Disposition.csv